/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Project4;

import org.junit.Test;
import static org.junit.Assert.*;

public class Project4Test {
    @Test public void testAppHasAGreeting() {
        
    }
}
